import LocalizedStrings from './LocalizedStrings';

export default strings = new LocalizedStrings({
  "en": {
    had_connected: 'Connected',
    unconnected: 'Unconnected',
    connecting: 'Connecting...',
    scaning: 'Connecting...',
    reconnect: 'Reconnect',
    isConnected: 'isConnected',
    notConnected: 'Not connected',
    disconnecting: 'Disconnecting...',
    loading: 'Loading……',
    connect_fail: 'Not connected',
    setting: "Setting",
    more_setting: "MoreSetting",
    featureSetting: 'Function settings',
    commonSetting: 'Common settings',
    device_more_activity_rename: 'Rename',
    locationManagement: 'Locations',
    shareDevice: 'Share device',
    device_more_activity_firmware_update: 'Check for firmware updates',
    device_more_activity_unbind: 'Remove device',
    addToDesktop: 'Add to Home screen',
    licenseAndPolicy: 'User Agreement & Privacy Policy',
    device_more_activity_feedback: 'Feedback',
    device_more_activity_license: 'User Agreement',
    device_more_activity_privacy: ' Privacy Policy ',
    delete_device: 'Delete Device',
    security_setting: "Security setting",
    faq: "FAQ",
    confirm: 'Confirm',
    cancel: 'Cancel',
    save: 'Save',
    mac_address: 'MAC Adress',
    ok: "Ok",
    failed: 'Request fail',
    netDisConnect: 'Please check the network',
    intelligence: 'Automation',
    add_failed: 'Add failure',
    license: 'Software Licensing and Service Agreement',
    privacy: 'Privacy protocol',
    power: 'Main switch',
    light_power: 'Light  switch',
    fan_power: 'Fan switch',
    click_see_more: 'Click to see more',
    back_light: 'Click to back',
    fan_level: 'Fan speed',
    light_mode: 'Work mode',
    natural_fan: 'Natural wind',
    turn_roll: 'Reversal',
    timing_on_off: 'Timer',
    timing: 'Timer',
    addTiming: 'Add timer',
    edit_timing: 'Edit timer',
    custom: 'Custom',
    repeat: 'Repeat',
    device_action: 'Equipment action',
    execute_once: 'Execute once',
    every_day: 'Everyday',
    working_day: 'Workday',
    weekend: 'Weekend',
    Monday: 'Monday',
    Tuesday: 'Tuesday',
    Wednesday: 'Wednesday',
    Thursday: 'Thursday',
    Friday: 'Friday',
    Saturday: 'Saturday',
    Sunday: 'Sunday',
    time: 'Time',
    fanOnOff: 'Fan switch',
    lightOnOff: 'Light  switch',
    open: 'On',
    close: 'Off',
    delete_timing: 'Delete timer',
    delete_timing_task: 'Are you sure to delete the timer',
    fan_open: 'Turn on the fan',
    fan_colse: 'Turn off the fan',
    light_open: 'Turn on',
    light_colse: 'Turn off',
    natural: 'Natural Wind',
    sleep: 'Sleep Wind',
    comfor: 'Comfortable Wind',
    smart: 'Smart Wind',
    fan_impeller: 'Fan Impeller',
    auxiliary_light_switch: 'Auxiliary Light Switch',
    tips: 'Tips',
    ensure_turn_roll: 'Please confirm to turn on normal mode？',
    ensure_turn_roll2: 'Please confirm to turn on reverse mode？',
    collect: 'Collect',
    timer: 'Timer',
    count_time: 'Countdown',
    collect_name: 'Collection name',
    collect_name_is_null: 'Please enter your favorite name',
    collect_name_too_long: 'Collection name too long',
    brightness: (x) => `Brightness： ${ x }%, `,
    temp: (x) => `Color temperature： ${ x }k`,
    brightness2: (x) => `Brightness： ${ x }%`,
    temp2: (x) => `Color temperature： ${ x }k`,
    brightness3: (x) => `Brightness${ x }%`,
    temp3: (x) => `Color temperature${ x }k`,
    brightness4: (x) => `Bri${ x }%`,
    temp4: (x) => `CT${ x }k`,
    rename: 'Rename',
    delete: 'Delete',
    default: 'Default status',
    power_on_to_restore_lighting_function: 'Last light mode',
    last_light_mode_warming: 'After power on, restore the light before power\noff (on for more than 8s)',
    power_on_to_restore_lighting_function_tips: 'When it is turned on, the lamp will automatically save the light before the power failure. At the same time, it can achieve the effect of lighting scene switching by switching on and off, that is, it can realize the lighting scene switching without APP, speaker and intelligent scene linkage operation',
    power_on_to_restore_lighting_function_tips2: 'Function description：\na:Power on to restore the lighting function: the lamp is in the power on state, and the light state changes or remains unchanged due to the control of APP and speaker instructions. As long as the light is executed for more than 8 seconds, the lamp will automatically save the current light state. When the power is off,' +
            'When the power is turned on again, the lamp will return to the light state before the power is cut off\nb:Power on and switch the light\'s profile (the profile is preset and can\'t be modified)\nStep 1. No more than 7 seconds after power on, and then power off (more than 8 seconds)\nStep 2. Power on again, the light will switch to light mode. If the light mode is not suitable, you need to perform step 1\nTip: when performing the function of "power on and switch lighting scene", please do not operate 8 times in 30 seconds. Avoid lamps entering: distribution network state, and clear the current network settings.',
    power_on_to_open_light_function: 'Fixed light mode',
    power_on_to_open_light_function_tips: 'Save the current light state and turn on the light\nin this state after power on',
    fix_light_mode_on: 'Saved light state',
    tips1: 'Click Save to save the current lighting status of the device\nTip: turn off the light, do not save',
    traverse_switch: 'Smart switch',
    sleep_aid_switch: 'Sleep aid switch',
    wake_up_switch: 'Wake up switch',
    awake_setting: 'Wake up settings',
    wake_up_now: 'Wake up now',
    timed_wake_up: 'Timed wake up',
    wake_up_now_tips: 'Gradually turn on the\nlight within 30 minutes',
    read: 'Read',
    video: 'Movie',
    night_light: 'night light',
    fixed_light_mode: 'Fixed light mode',
    fixed_light_mode_tips: 'After the mode is turned on, the switch will not support the segmentation function. Are you sure to turn it on?',
    device_is_connect: 'Gateway connected',
    ble_is_connect: 'Bluetooth connected',
    custom_max_20: 'Collection cannot exceed 20',
    duplicate_custom_theme_name: 'Duplicate custom theme name',
    collect_input_tips: 'Input the name (within 10 words)',
    delete_collect: 'Delete collection',
    delete_collect_tips: 'Are you sure to delete this collection?',
    day_light: 'Sunlight',
    moon_light: 'Moonlight',
    warming: 'Cozy',
    sleep_aid: 'Sleep',
    awake: 'Awaken',
    use_now: 'Switch',
    used: 'Used',
    ble_direct_connect: 'BLE Connect',
    count_down_tips: 'Countdown not available with lights off',
    turn_off_cant_use_mode: 'This mode cannot be enabled when the lights are off',
    text_brightness: 'Brightness',
    text_temp: 'Color temperature',
    scene_mode: 'Scene mode',
    computer: 'Computer',
    intelligence_tips: 'Experience more custom\nintelligent operations',
    my_mode: 'My mode',
    通电状态: 'Power on status',
    开灯状态: 'Turn on light status',
    开灯: 'Turn on the light',
    关灯: 'Turn off the light',
    开灯提示语: 'After the lamp is powered on, it turns on by default (This state is the factory default state)',
    关灯提示语: 'If the last power on is greater than 8 seconds, after the lamp is powered on, the default Enter the light off state;',
    通电状态提示语: 'In order to solve the problem of restoring power supply after the power grid runs out, which causes the lamps to turn on by default, thus affecting the user\'s rest',
    通电状态提示语2: 'In order to solve the problem of restoring power supply after the power grid runs out, which causes the lamps to turn on by default, thus affecting the user\'s rest;\n\nWhen using a mechanical switch, it needs to be switched twice in 8 seconds to trigger the light on',
    关灯前状态: 'Status before light off',
    关灯前状态提示: 'Turn on the lamp and enter the state before turning off the lamp (if the lamp is turned on and off within 8 seconds, the lamp will cycle to switch the light mode)',
    leedarson关灯前状态提示: 'Turn on the lamp and enter the state before',
    默认状态: 'Default status',
    默认状态提示语: 'Turn on the light to enter the default state',
    当前灯具默认状态: 'Current lamp default state',
    更新: 'Update',
    开启灵动开关: 'Turn on the "smart switch" function',
    开启灵动开关说明: 'Function description of smart switch \n' +
            '\n' +
            '1. If this smart light supports the use with a wall switch with a "smart switch" function, this function can be turned on to realize that the device is still powered on and online when the light is off, and supports intelligent control. \n' +
            '\n' +
            '2. If the wall switch supports the "smart switch" function, the switch state should be powered off when the switch is pressed and powered on when it is released. Wall switches that support the "smart switch" function include: xiaomijia wall switch and yeelight ice switch. If other switches support the "smart switch" function, please consult the corresponding switch manufacturer. \n' +
            '\n' +
            'precautions \n' +
            '\n' +
            '1. please make sure to install a wall switch that supports the "smart switch" function, and make sure to turn on this function after configuring the wall switch to the "smart switch" state, otherwise it may cause abnormal control. \n' +
            '\n' +
            '2. When the lamp is turned off by using the "smart switch" function, APP and other intelligent control methods, the lamp will still be in the energized state. Do not touch, check and repair the lamp in this state.',
    开启: 'Turn on',
    请阅读以下注意事项: 'Please read the following notes',
    灵动开关弹窗提示: '1. Please make sure to install a wall switch that supports the "smart switch" function, and make sure to turn on this function after configuring the wall switch to the "smart switch" state, otherwise it may cause abnormal control. \n' +
            '\n' +
            '2. When the lamp is turned off by using the "smart switch" function, APP and other intelligent control methods, the lamp will still be in the energized state. Do not touch, check and repair the lamp in this state.',
    助眠唤醒模式设置: 'Sleep aid / Wake-up mode setting',
    助眠模式设置: 'Sleep aid mode setting',
    持续时长: 'Duration',
    自定义起始状态: 'Custom start state',
    自定义起始状态提示: 'When off, the initial state is the current on\nstate',
    唤醒模式设置: 'Wake up mode setting',
    自定义最终状态: 'Customize final status',
    自定义最终状态提示: 'When off, the final state is the maximum\nbrightness of white light',
    助眠提示: 'Description of sleep aid mode:\n' +
            'Turn off the light slowly from the initial state to help\nusers sleep naturally.',
    唤醒提示: 'Wake up mode description:\n' +
            'Slowly turn on the light from the off state to the\nfinal state to help users wake up naturally.',
    分钟: 'min',
    助眠时长设定: 'Sleep aid duration setting',
    唤醒时长设定: 'Wake up duration setting',
    编辑我的模式: 'Edit my mode',
    起始状态设置: 'Initial state setting',
    最终状态设置: 'Final status settings',
    cant_use: 'This function can only be used with Bluetooth mesh gateway',
    更新失败: 'Update failed, lamp is off',
    更新成功: 'Update success',
    已关闭: 'Closed',
    遥控器: 'Remote control',
    起夜灯模式设置: 'Night light mode setting',
    专业设置: 'Professional settings',
    功能说明: 'Function description',
    功能说明1: '1. Remote control code matching: Long press the remote control power on button, and then click the [Remote Control Code Matching] button below to complete the pairing. After the pairing is successful, the remote control can control the lamps.',
    功能说明2: '2. Clear all remote controllers: the lamps will clear all the information of the remote controllers that have been bound, and users need to pair the remote controllers again.',
    遥控器对码: 'Remote control code matching',
    清除所有遥控器: 'Clear all remote controls',
    清除所有遥控器提示: 'The lamp is about to clear all the bound remote control information, and users need to re code when using the remote control!',
    清除: 'Eliminate',
    起夜灯模式1: 'After the night light mode is turned on, use the APP or remote control to turn on the light within the set time period, and the light will automatically enter the night light state (The lowest brightness). When the user gets up at midnight and turns on the light, the light will not be too bright.',
    起夜灯模式2: 'The night light status is only triggered when the APP or remote control is used to turn on the lights. If the lights are powered on after the power is cut off, the night light status will not be triggered.',
    起夜灯模式: 'Night light mode',
    start_time: 'Start time',
    end_time: 'End time',
    开灯渐变时长: 'Gradual change max duration of\nlight on',
    关灯渐变时长: 'Gradual change max duration of\nlight off',
    调光渐变时长: 'Dimming gradient max duration',
    重置所有设置: 'Reset All Settings',
    重要提示: 'Important Tips',
    重置设置提示: 'Please operate with caution! After resetting all settings, all user defined settings will be cleared and restored to the factory state. Are you sure you want to reset all settings?',
    ms: 'ms',
    s: 's',
    最低亮度: 'Minimum brightness',
    应用成功: 'Success',
    开启辅光: 'Open Help light',
    关闭辅光: 'Close Help light',
    蓝牙网关信号: 'Bluetooth gateway signal',
    无网关: 'direct connection',
    已离线: 'Offline',
    灯光变化设置: 'Light variation settings',
    渐变效果: 'Gradient effect',
    立即变化: 'Change immediately',
    产品功能信息获取失败: 'Failed to obtain product function information, please try again',
    次日: 'Next day ',
    专业设置功能说明: 'During the lighting change process, if the dimming range of the light is too small to meet the maximum duration requirement of the gradient, the lamp will shorten the duration of the light change, prioritize ensuring the dimming experience of the lamp, and avoid discomfort such as light shaking.',
    唤醒模式: 'Wake up Settings',
    助眠设置: 'Sleep aid Settings',
    默认状态提示语2: 'Turn on the light and enter the default state (You can click the "Update" button below to update the current light state to the default state of the lamp)',

    呼吸: 'Breathing',
    律动: 'Rhythm',
    呼吸模式: 'Breathing',
    律动模式: 'Rhythm',
    灯光设置: 'Lighting settings',
    颜色变换方式: 'Color transformation\nmethod',
    渐变: 'Gradient',
    跳变: 'Quick',
    颜色变换速度: 'Color change speed',
    慢: 'slow',
    快: 'fast',
    生物节律功能: 'Biorhythms',
    生物节律功能设置: 'Biorhythms setting',
    灯光跟随生物节律自动变化: 'Light automatically changes according\nto biological rhythms',
    开启生物节律功能: 'Turn on the "Biorhythms" function',
    开启生物节律功能tips: 'Functional Description of Biological Rhythm\n\nThe biological rhythm function is based on the Circadian clock of the human body, combined with the natural light law to design 24-hour light brightness, color temperature changes, improve the human body\'s work and rest rules, and achieve the purpose of making users comfortable and healthy.',
    一: 'Mon',
    二: 'Tue',
    三: 'Wed',
    四: 'Thur',
    五: 'Fri',
    六: 'Sat',
    日: 'Sun',
    起床: 'Wake up',
    中午: 'Noon',
    午休: 'Lunch break',
    午起: 'From noon',
    傍晚: 'Rvening',
    入睡: 'Sleep',
    变光时长: 'Dimming duration: ',
    变光时长2: 'Dimming duration',
    重置: 'Reset',
    到达目标亮度时间: 'Time to reach target brightness',
    起床设置: 'Wake up settings',
    中午设置: 'Noon setting',
    午休设置: 'Lunch break settings',
    午起设置: 'From noon setting',
    傍晚设置: 'Evening setting',
    入睡设置: 'Sleep settings',
    开关灯切换灯光颜色: 'Segmenting functions',
    开关灯切换灯光颜色提示: 'After turning on, when the lamp is powered on or off within 8 seconds, the light color will switch.(Be careful not to operate the switch more than 8 times in a short period of time, which may cause the lamp to enter the distribution network state）',
    指数调光: 'Exponential dimming',
    灯光: 'Light'
  },
  "zh": {
    had_connected: '蓝牙已连接',
    unconnected: 'mesh网关未连接',
    connecting: '连接中...',
    scaning: '连接中...',
    reconnect: '重连',
    isConnected: '已连接',
    notConnected: '未连接',
    disconnecting: '断开连接中...',
    connect_fail: '未连接',
    loading: '加载中……',
    setting: '设置',
    more_setting: '更多设置',
    featureSetting: '功能设置',
    commonSetting: '通用设置',
    device_more_activity_rename: '设备名称',
    locationManagement: '位置管理',
    shareDevice: '设备共享',
    device_more_activity_firmware_update: '检查固件更新',
    device_more_activity_unbind: '删除设备',
    addToDesktop: '添加桌面快捷方式',
    licenseAndPolicy: '使用条款和隐私政策',
    device_more_activity_feedback: '反馈',
    device_more_activity_license: '使用条款',
    device_more_activity_privacy: '隐私政策',
    delete_device: '删除设备',
    security_setting: "安全设置",
    faq: "常见问题",
    confirm: '确定',
    cancel: '取消',
    save: '保存',
    mac_address: 'MAC地址',
    ok: "好的",
    failed: '请求失败',
    netDisConnect: '请检查网络',
    intelligence: '智能场景',
    add_failed: '添加失败，定时已存在',
    license: '软件许可及服务协议',
    privacy: '隐私协议',
    power: '总开关',
    light_power: '光源开关',
    fan_power: '风扇开关',
    click_see_more: '点击查看更多',
    back_light: '点击收起',
    fan_level: '风扇档位',
    light_mode: '工作模式',
    natural_fan: '自然风',
    turn_roll: '反转',
    timing_on_off: '定时开关',
    timing: '定时',
    addTiming: '添加定时',
    edit_timing: '编辑定时',
    custom: '自定义',
    repeat: '重复',
    device_action: '设备动作',
    execute_once: '执行一次',
    every_day: '每天',
    working_day: '工作日',
    weekend: '周末',
    Monday: '周一',
    Tuesday: '周二',
    Wednesday: '周三',
    Thursday: '周四',
    Friday: '周五',
    Saturday: '周六',
    Sunday: '周日',
    time: '时间',
    fanOnOff: '风扇开关',
    lightOnOff: '光源开关',
    open: '开启',
    close: '关闭',
    delete_timing: '删除定时',
    delete_timing_task: '是否删除定时任务',
    fan_open: '风扇开启',
    fan_colse: '风扇关闭',
    light_open: '开启',
    light_colse: '关闭',
    natural: '自然风',
    sleep: '睡眠风',
    comfor: '舒适风',
    smart: '智能风',
    fan_impeller: '风扇叶轮',
    auxiliary_light_switch: '辅助灯开关',
    tips: '提示',
    ensure_turn_roll: '请确认打开正常模式？',
    ensure_turn_roll2: '请确认打开反转模式？',
    collect: '收藏夹',
    timer: '定时',
    count_time: '倒计时开关',
    collect_name: '收藏名字',
    collect_name_is_null: '请输入收藏名字',
    collect_name_too_long: '收藏名字过长',
    text_brightness: '亮度',
    text_temp: '色温',
    brightness: (x) => `亮度： ${ x }%, `,
    temp: (x) => `色温： ${ x }K`,
    brightness2: (x) => `亮度： ${ x }%`,
    temp2: (x) => `色温： ${ x }K`,
    brightness3: (x) => `亮度${ x }%`,
    temp3: (x) => `色温${ x }K`,
    brightness4: (x) => `亮度${ x }%`,
    temp4: (x) => `色温${ x }K`,
    rename: '重命名',
    delete: '删除',
    default: '默认状态',
    power_on_to_restore_lighting_function: '上次灯光模式',
    last_light_mode_warming: '通电后恢复断电前灯光（亮起8S以上）状态',
    power_on_to_restore_lighting_function_tips: '开启后,灯具将自动保存断电前的灯光，同时也具备通过开关通、断电的动作去达到灯光情景切换的效果，即：无需APP、音箱、智能场景联动操作就可以实现灯光情景切换',
    power_on_to_restore_lighting_function_tips2: '功能描述：\na:通电恢复灯光功能：灯具处于通电状态，灯光受APP、音箱指令的控制而引起灯光状态变化、或者灯光状态保持不变，只要灯光执行完毕后，超过8秒钟以上，灯具自行会保存当前灯光状态。当断电后，' +
            '再通电的时候灯具就会恢复断电前的灯光状态\nb:通电切换灯的情景模式（情景模式为预设，不可修改）：\n步骤1. 通电后不超过7秒，然后断电（超过8秒）\n步骤2. 再通电，灯将会切换灯光模式。如果该灯光模式不合适，需要执行步骤1即可\n提示：在执行"通电切换灯光情景"功能时，请不要在30秒内，连续操作8次。避免灯具进入：配网状态，并清除当前网络设置。',
    power_on_to_open_light_function: '固定灯光模式',
    power_on_to_open_light_function_tips: '保存当前灯光状态，通电后以此状态亮灯',
    fix_light_mode_on: '已保存灯光状态',
    tips1: '点击保存"保存"，即可将设备当前灯光状态保存\n提示：关灯状态，不进行保存',
    traverse_switch: '灵动开关',
    sleep_aid_switch: '助眠开关',
    wake_up_switch: '唤醒开关',
    awake_setting: '唤醒设置',
    wake_up_now: '立即唤醒',
    timed_wake_up: '定时唤醒',
    wake_up_now_tips: '30分钟内逐渐亮灯',
    read: '阅读',
    video: '影院',
    night_light: '夜灯',
    fixed_light_mode: '固定灯光模式',
    fixed_light_mode_tips: '选择该模式后，开关将不支持分段功能，是否确定选择？',
    device_is_connect: '网关已连接',
    ble_is_connect: '蓝牙已连接',
    custom_max_20: '收藏不能超过20个',
    duplicate_custom_theme_name: '自定义名称已存在',
    collect_input_tips: '输入收藏名称(10字以内)',
    delete_collect: '删除收藏',
    delete_collect_tips: '确定删除该收藏吗？',
    day_light: '日光',
    moon_light: '月光',
    warming: '温馨',
    sleep_aid: '助眠',
    awake: '唤醒',
    use_now: '切换',
    used: '使用中',
    ble_direct_connect: '蓝牙直连',
    count_down_tips: '关灯状态下倒计时不可用',
    turn_off_cant_use_mode: '关灯状态下无法启用该模式',
    scene_mode: '情景模式',
    computer: '电脑',
    intelligence_tips: '体验更多自定义智能操作',
    my_mode: '我的模式',
    通电状态: '通电状态',
    开灯状态: '开灯状态',
    开灯: '开灯',
    关灯: '关灯',
    开灯提示语: '灯具通电后，默认开灯（此状态为出厂默认状态）',
    关灯提示语: '若上次通电时大于8秒，灯具通电后，默认进入关灯状态',
    通电状态提示语: '此功能为了解决电网没电之后恢复供电，导致灯具默认开灯，从而影响用户休息的问题',
    通电状态提示语2: '此功能为了解决电网没电之后恢复供电，导致灯具默认开灯，从而影响用户休息的问题；\n\n使用机械开关时，需要在8秒内开关2次才能触发开灯',
    关灯前状态: '关灯前状态',
    关灯前状态提示: '开灯进入关灯前状态',
    leedarson关灯前状态提示: '开灯进入关灯前状态',
    默认状态: '默认状态',
    默认状态提示语: '开灯进入默认状态',
    当前灯具默认状态: '当前灯具默认状态',
    更新: '更新',
    开启灵动开关: '开启“灵动开关”功能',
    开启灵动开关说明: '灵动开关功能说明\n' +
            '\n' +
            '1.若本智能灯支持搭配具有“灵动开关”功能的墙壁开关使用，可打开此功能，实现关灯状态下设备仍通电在线，并支持智能控制。\n' +
            '\n' +
            '2.若墙壁开关支持“灵动开关”功能，开关状态应在开关按下时断电，松开时通电。支持“灵动开关”功能的墙壁开关有：小米米家墙壁开关、Yeelight凌动开关。其他开关是否支持“灵动开关”功能，请咨询对应开关厂家。\n' +
            '\n' +
            '注意事项\n' +
            '\n' +
            '1.请确保安装支持“灵动开关”功能的墙壁开关，并确保将墙壁开关配置为“灵动开关”状态后打开此功能，否则可能引起控制异常。\n' +
            '\n' +
            '2.灯具使用“灵动开关”功能、APP等智能控制方式关灯时，灯具仍会处于通电状态，请勿在此状态下触碰、检查、维修灯具。',
    开启: '开启',
    请阅读以下注意事项: '请阅读以下注意事项',
    灵动开关弹窗提示: '1.请确保安装支持“灵动开关”功能的墙壁开关，并确保将墙壁开关配置为“灵动开关”状态后打开此功能，否则可能引起控制异常。\n' +
            '\n' +
            '2.灯具使用“灵动开关”功能、APP等智能控制方式关灯时，灯具仍会处于通电状态，请勿在此状态下触碰、检查、维修灯具。',
    助眠唤醒模式设置: '助眠/唤醒模式设置',
    助眠模式设置: '助眠模式设置',
    持续时长: '持续时长',
    自定义起始状态: '自定义起始状态',
    自定义起始状态提示: '关闭时，起始状态为当前开灯状态',
    唤醒模式设置: '唤醒模式设置',
    自定义最终状态: '自定义最终状态',
    自定义最终状态提示: '关闭时，最终状态为白光最大亮度',
    助眠提示: '助眠模式说明：\n从起始状态缓慢灭灯，帮助用户自然睡眠。',
    唤醒提示: '唤醒模式说明：\n从灭灯状态缓慢亮灯至最终状态，帮助用户自然苏醒。',
    分钟: '分钟',
    助眠时长设定: '助眠时长设定',
    唤醒时长设定: '唤醒时长设定',
    编辑我的模式: '编辑我的模式',
    起始状态设置: '起始状态设置',
    最终状态设置: '最终状态设置',
    cant_use: '该功能需要搭配蓝牙Mesh网关才可以使用',
    更新失败: '更新失败，灯具处于关灯状态',
    更新成功: '更新成功',
    已关闭: '已关闭',
    遥控器: '遥控器',
    起夜灯模式设置: '起夜灯模式设置',
    专业设置: '专业设置',
    功能说明: '功能说明',
    功能说明1: '1.遥控器对码：长按遥控器开机键，再点击下方【遥控器对码】按钮完成配对，配对成功后，遥控器即可遥控灯具。',
    功能说明2: '2.清除所有遥控器：灯具将清除所有已绑定的遥控器信息，用户使用遥控器需要重新对码配对。',
    遥控器对码: '遥控器对码',
    清除所有遥控器: '清除所有遥控器',
    清除所有遥控器提示: '灯具即将清除所有已绑定的遥控器信息，用户使用遥控器需要重新进行对码！',
    清除: '清除',
    起夜灯模式1: '起夜灯模式开启后，在设定的时间段内，使用APP或\n遥控器开灯，灯会自动进入起夜灯状态(亮度最暗)，\n在用户半夜起床开灯时，灯光不会太亮。',
    起夜灯模式2: '起夜灯状态仅在使用APP或遥控器开灯时触发，如灯\n具断电后再上电，不会触发起夜灯状态。',
    起夜灯模式: '起夜灯模式',
    start_time: '开始时间',
    end_time: '结束时间',
    开灯渐变时长: '开灯渐变最大时长',
    关灯渐变时长: '关灯渐变最大时长',
    调光渐变时长: '调光渐变最大时长',
    重置所有设置: '重置所有设置',
    重要提示: '重要提示',
    重置设置提示: '请谨慎操作！重置所有设置后，所有用户的自定义设置项将清除并恢复至出厂状态，请确认是否重置所有设置？',
    ms: '毫秒',
    s: '秒',
    最低亮度: '最低亮度',
    应用成功: '应用成功',
    开启辅光: '开启辅光',
    关闭辅光: '关闭辅光',
    蓝牙网关信号: '蓝牙网关信号',
    无网关: '无网关,直连状态',
    已离线: '已离线',
    灯光变化设置: '灯光变化设置',
    渐变效果: '渐变效果',
    立即变化: '立即变化',
    产品功能信息获取失败: '产品功能信息获取失败，请重试',
    次日: '次日 ',
    专业设置功能说明: '灯光变化过程中，若灯光调光区间太小，达不到渐变最大时长要求，灯具会缩短灯光变化时长，优先保障灯具调光体验，避免灯光抖动等不适感。',
    唤醒模式: '唤醒设置',
    助眠设置: '助眠设置',
    默认状态提示语2: '开灯进入默认状态（可点击下方"更新"按钮，将当前亮灯状态，更新为灯具默认状态）',


    呼吸: '呼吸',
    律动: '节拍',
    呼吸模式: '呼吸模式',
    律动模式: '节拍模式',
    灯光设置: '灯光设置',
    颜色变换方式: '颜色变换方式',
    渐变: '渐变',
    跳变: '立变',
    颜色变换速度: '颜色变换速度',
    慢: '慢',
    快: '快',
    生物节律功能: '生物节律功能',
    生物节律功能设置: '生物节律功能设置',
    灯光跟随生物节律自动变化: '灯光跟随生物节律自动变化',
    开启生物节律功能: '开启“生物节律”功能',
    开启生物节律功能tips: '生物节律功能说明\n\n生物节律功能是以人体生物钟为基础，结合自然光照规律来设计24小时的光照亮度、色温变化，提高人体的作息规律，达到使用户舒适、健康的目的。',
    一: '一',
    二: '二',
    三: '三',
    四: '四',
    五: '五',
    六: '六',
    日: '日',
    起床: '起床',
    中午: '中午',
    午休: '午休',
    午起: '午起',
    傍晚: '傍晚',
    入睡: '入睡',
    变光时长: '变光时长: ',
    变光时长2: '变光时长',
    重置: '重置',
    到达目标亮度时间: '到达目标亮度时间',
    起床设置: '起床设置',
    中午设置: '中午设置',
    午休设置: '午休设置',
    午起设置: '午起设置',
    傍晚设置: '傍晚设置',
    入睡设置: '入睡设置',
    开关灯切换灯光颜色: '分段功能',
    开关灯切换灯光颜色提示: '打开后，灯具在8s内通断电时，会切换灯光颜色。（注意避免短时间开关操作超过8次，导致灯具进入配网状态）',
    指数调光: '指数调光',
    灯光: '灯光'
  }
});

